import { useState } from 'react'


function RazorpayPayment() {

  const [address,setaddress] = useState('');
  const handleformsubmit = async (e)=>{
  
      e.preventDefault();
        
      const options = {
        key: "rzp_test_qnMtpL2VUranII", // Your Razorpay key_id
        amount: 5 * 100, // Amount in paise
        currency: "INR",
        name: "Your Company Name",
        description: "Test Transaction",
        order_id: "order_PX19rTUToWXGM6", // Generated by the backend
        handler: async function (response) {
          // Step 3: Send payment details and address to backend
        console.log(response);
            const paymentData = {
              
                razorpay_order_id: response.razorpay_order_id,
                razorpay_payment_id: response.razorpay_payment_id,
                razorpay_signature: response.razorpay_signature
            
            }
            console.log("the paymentdata is",paymentData)
          const verifyResponse = await fetch("http://localhost:8000/api/cart/verify_order", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(paymentData,address),
          });

          const result = await verifyResponse.json();
          console.log('result is from verification',result)
        
          if (result.ok) {
           
            alert("Payment Successful! Order placed.");
          } else {
            alert("Payment verification failed.");
          }
        },
        prefill: {
          name: "John Doe",
          email: "johndoe@example.com",
          contact: "9999999999",
        },
        theme: {
          color: "#3399cc",
        },
      };

      const rzp = new window.Razorpay(options);
      rzp.open();
 
   }
 return(
  <>
      <div>
          <p>checkOut</p>

           <form onSubmit={handleformsubmit}>
                 <input type="text" onChange={(e)=>setaddress(e.target.value)}/>
                <button type='submit'>CheckOut</button>
           </form>
      </div>
  </>
  )
}

export default RazorpayPayment;
