import { chekOut, razorpayOrderid } from '../services/Api';


function RazorpayPayment() {

  const handleformsubmit = async (onsuccess,onfailure)=>{
  
    try{
      const res = await razorpayOrderid()
      console.log("razorpayOrderid",res)
      if(res.success === true){
        const {orderId,key,amount} = res.data;


      const options = {
        key:key, // Your Razorpay key_id
        amount:amount, // Amount in paise
        currency: "INR",
        name: "Your Company Name",
        description: "Test Transaction",
        order_id: orderId, // Generated by the backend
        handler: async function (response) {
          // Step 3: Send payment details and address to backend
        try{
        console.log(response);
            const paymentData = {
              
                razorpay_order_id: response.razorpay_order_id,
                razorpay_payment_id: response.razorpay_payment_id,
                razorpay_signature: response.razorpay_signature
            
            }
            console.log("the paymentdata is",paymentData)

            const res = await chekOut(paymentData)
            console.log("response of the paymentData",res)
        
          if (res.success === true) {
             console.log('payment verification success')
             onsuccess('payment verification success ')
          } else {
             onfailure('payment verification faliled please try again')
          }
        }catch(err){
          console.log("error happen in the verification payment",err.response)
       }
        },
        prefill: {
          name: "John Doe",
          email: "johndoe@example.com",
          contact: "9999999999",
        },
        theme: {
          color: "#3399cc",
        },
      };
    
      const rzp = new window.Razorpay(options);
      rzp.open();
    }
  }catch(err){
    console.log("error occur in the razorpay_order_id",err.response)
  }
   }
 
   return handleformsubmit;
}

export default RazorpayPayment;
