name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - master  # Deploy only when changes are pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the Node.js version your project requires
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci  # Faster, cleaner install for production use

      # Step 4: Build the frontend application
      - name: Build application
        run: npm run build  # Ensure your package.json has a "build" script

            # Step 5: Deploy to Vercel
           # Step 5: Deploy to Vercel
           # Step 5: Deploy to Vercel
            # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN --yes

